version: '3.3'

services:
  db:
    image: mysql:8
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sara
    ports:
      - "3308:3306"
      #this is so that this MySQL container can also be accesed in the hostOS using localhost:3308 (127.0.0.1:3308)

  sara:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
      - '50000:50000'
    
volumes:
    db_data: {}