version: '3.3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    #volumes:
       #- db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sara
    ports:
      - "3308:3306"
      #this is so that this MySQL container can also be accesed in the hostOS using localhost:3308 (127.0.0.1:3308)
    command: --default-authentication-plugin=mysql_native_password

  sara:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DB_NAME: sara
      DB_HOST: db
      DB_USER: root
      DB_PASS: password
      DB_PORT: 3306

      NODE_ENV: development
    depends_on:
      - db

#  jenkins:
#    image: jenkins/jenkins:lts
#    ports:
#      - '8081:8080'
#      - '50000:50000'
#    volumes:
#      - 'jenkins_data:/var/jenkins_home'

#volumes:
#  jenkins_data:
#    driver: local