FROM node:11.12
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm install -g nodemon 

# RUN npm install -g knex
# RUN knex migrate:latest

RUN apt-get update && apt-get install -y \
  nano
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 3000

# CMD "./bin/start-dev"
CMD [ "npm", "start" ]